services:
  sqlserver:
    container_name: sqlserver_dev
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStrongP@ssw0rd!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      #- sqlserver_data:/var/opt/mssql # -->Esta linea una vez restaurada la base de datos
      #- sqlserver_data:/var/opt/
      - ./backup:/var/opt/mssql/backup #-->Esta linea mientras restauras la base de datos
    restart: unless-stopped

volumes:
  sqlserver_data:
